### ISSUE TITLE
allow to define key, certs etc as content

### ISSUE THREAD

**Issue by toepi** [inkblot/puppet-openvpn#2]
To define keys, certs directly in hiera it should be possible to define it as content too instead as source only.

Drawbacks: Every key/cert has two parameters like ca_cert_source and ca_cert_content and a Validation rule with prevent Setting of both (one must be leave undef - see file resource)

Take a look at: https://github.com/rjpearce/puppet-opendkim/commit/ebfc8bfb75f567352ac62d52913c80d0594faf61

**Comment by inkblot** [comment]
Could you try using #3 and let me know how it goes? Thanks!

**Comment by toepi** [comment]
sry for the delay.

currently I'm not able to test your module (Could not find class ::defaults for ... modules/openvpn/manifests/init.pp:7:5 on node)

One small change: you not define content and source, which mean the caller must set one of them to undef or '' - i think it would be better to set both to undef in this module?

**Comment by inkblot** [comment]
Let's continue the discussion on PR #3.
